### ISSUE TITLE
discord.js not found(RESOLVED)

### ISSUE THREAD

**Issue by FatalMC** [SharkFinPro/Galaxy-RP-Bot#1]
Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ivan/Galaxy-RP-Bot/source/bot.js:43:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by FatalMC** [comment]
Resolved no need to worry...

**Comment by SharkFinPro** [comment]
lol u neeed to install modules
